kind = "mobile"
previewPath = "/mobile/"
title = "Caktus Productions Mobile"
version = "1.0.0"
id = "artifacts/caktus-portfolio-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 25841

[services.development]
run = "pnpm --filter @workspace/caktus-portfolio-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/caktus-portfolio-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/caktus-portfolio-mobile", "run", "serve" ]

[services.env]
PORT = "25841"
BASE_PATH = "/mobile/"
