const colors = {
  light: {
    text: "#0a0a0f",
    tint: "#9333ea",
    background: "#ffffff",
    foreground: "#0a0a0f",
    card: "#f4f4f8",
    cardForeground: "#0a0a0f",
    primary: "#9333ea",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f5",
    secondaryForeground: "#1a1a24",
    muted: "#f0f0f5",
    mutedForeground: "#666677",
    accent: "#6366f1",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e2e2ea",
    input: "#e2e2ea",
  },
  dark: {
    text: "#ffffff",
    tint: "#9333ea",
    background: "#0a0a0f",
    foreground: "#f0f0f5",
    card: "#111117",
    cardForeground: "#f0f0f5",
    primary: "#9333ea",
    primaryForeground: "#ffffff",
    secondary: "#1a1a24",
    secondaryForeground: "#d0d0e0",
    muted: "#1a1a24",
    mutedForeground: "#8888aa",
    accent: "#6366f1",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e1e2e",
    input: "#1e1e2e",
  },
  radius: 10,
};

export default colors;
