"use strict";
// Vercel serverless function entry point — committed so Vercel sees the function at repo-clone time.
// bundle.js + pino workers are generated by buildCommand before this runs.
module.exports = require("./bundle.js");
